#! /bin/sh -e

parameters=($@)

# Merge
gs -dBATCH -dNOPAUSE -q -sDEVICE=pdfwrite -sOutputFile=/tmp/tmp.pdf ${parameters[@]:1}

# Compress
gs -sDEVICE=pdfwrite -dCompatibilityLevel=1.4 -dPDFSETTINGS=/default -dNOPAUSE -dQUIET -dBATCH -dDetectDuplicateImages -dCompressFonts=true -r150 -sOutputFile=${parameters[0]} /tmp/tmp.pdf

rm /tmp/tmp.pdf
